// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXpubYweFjB0S8Q4SCQ8ezfzQnxQg3qk',
    appId: '1:751634585452:web:45a91b38766292695dc549',
    messagingSenderId: '751634585452',
    projectId: 'cookfit-526e0',
    authDomain: 'cookfit-526e0.firebaseapp.com',
    storageBucket: 'cookfit-526e0.appspot.com',
    measurementId: 'G-LBS44KPXQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX3YhyqdjxNocsp7ixuyt3yiVvVbXmwmA',
    appId: '1:751634585452:android:9bdebb876b35675c5dc549',
    messagingSenderId: '751634585452',
    projectId: 'cookfit-526e0',
    storageBucket: 'cookfit-526e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuwHUHMdUjD9kwgGb9awxMUBrFe8GAN88',
    appId: '1:751634585452:ios:869df8a3eb87377e5dc549',
    messagingSenderId: '751634585452',
    projectId: 'cookfit-526e0',
    storageBucket: 'cookfit-526e0.appspot.com',
    iosBundleId: 'com.google.fireabase.presents.cookfit',
  );
}
